# Generated by Django 6.0.5 on 2026-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_user_alter_client_owner_alter_mailing_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Включена"),
        ),
    ]
